### ISSUE TITLE
building on intel dev cloud fails

### ISSUE THREAD

**Issue by fixerivan** [intel/hexl-fpga#27]
Hi, trying to test your project on the intel dev cloud as I dont have a physical fpga 

u177856@s001-n144:~/hexl-fpga-2.0$ cmake --build . --target emulation
Scanning dependencies of target emulation
[100%] Compiling for emulation
./compile.sh: 7: ./config.sh: kernels+= dyadic_multiply: not found
./compile.sh: 8: ./config.sh: kernels+= fwd_ntt: not found
./compile.sh: 9: ./config.sh: kernels+= inv_ntt: not found
./compile.sh: 10: ./config.sh: kernels+= keyswitch: not found
./compile.sh: 11: ./config.sh: kernels+= dyadic_multiply_keyswitch: not found
./compile.sh: 14: ./config.sh: config_dyadic_multiply+= -Xsboard=intel_s10sx_pac:pac_s10_usm: not found
./compile.sh: 15: ./config.sh: config_dyadic_multiply+= -Xsclock=400MHz: not found
./compile.sh: 18: ./config.sh: config_fwd_ntt+= -DNUM_NTT_COMPUTE_UNITS=1: not found
./compile.sh: 19: ./config.sh: config_fwd_ntt+= -DVEC=8: not found
./compile.sh: 20: ./config.sh: config_fwd_ntt+= -Xsboard=intel_s10sx_pac:pac_s10_usm: not found
./compile.sh: 21: ./config.sh: config_fwd_ntt+= -Xsclock=400MHz: not found
./compile.sh: 24: ./config.sh: config_inv_ntt+= -DNUM_INTT_COMPUTE_UNITS=1: not found
./compile.sh: 25: ./config.sh: config_inv_ntt+= -DVEC_INTT=8: not found
./compile.sh: 26: ./config.sh: config_inv_ntt+= -Xsboard=intel_s10sx_pac:pac_s10_usm: not found
./compile.sh: 27: ./config.sh: config_inv_ntt+= -Xsclock=360MHz: not found
./compile.sh: 30: ./config.sh: config_keyswitch+= -DCORES=1: not found
./compile.sh: 31: ./config.sh: config_keyswitch+= -Xsno-interleaving=DDR: not found
./compile.sh: 32: ./config.sh: config_keyswitch+= -Xshyper-optimized-handshaking=off: not found
./compile.sh: 33: ./config.sh: config_keyswitch+= -Xsboard=intel_s10sx_pac:pac_s10: not found
./compile.sh: 34: ./config.sh: config_keyswitch+= -Xsclock=240MHz: not found
./compile.sh: 37: ./config.sh: config_dyadic_multiply_keyswitch+= -DCORES=1: not found
./compile.sh: 40: ./config.sh: fpga_args+= -Xsbsp-flow=flat: not found
./compile.sh: 41: ./config.sh: fpga_args+= -Xsseed=789045: not found
[100%] Built target emulation

this is for a build with all config options OFF 

could you please test using the intel dev cloud environment? 

u177856@s001-n144:~/hexl-fpga-2.0$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

its the only way how to test / try your project without having to own a physical fpga

**Comment by ymeng-git** [comment]
Thanks for your information.  There are a couple of observations.  Firstly, emulation does not need a physical FPGA.  You can install oneAPI in your local environment and try emulation.   Secondly, the release has been validated on CentOS for PAC D5005 cards.  Due to the difference in how Ubuntu and CentOS handle shell commands, if you compile and run with Ubuntu, you would need to add "bash" in front of the scripts/shell command, eg. "bash ./config.sh" etc.  Could you try to workaround the difference from Ubuntu shell or try on CentOS?  Thanks.

**Comment by fixerivan** [comment]
thanks for the tip, after editing the compile.sh / config.sh shell scripts a bit I am able to compile emulation mode, for fpga mode the dyadic multiply kernel compiles but others do not

what I am seeing is for the next kernel:

dpcpp -Xshardware -fPIC -O3 -DNDEBUG -fintelfpga -shared -qactypes -Wno-ignored-attributes -Wno-return-type-c-linkage -Wno-unknown-pragmas -DFPGA_NTT_SIZE=16384 -o libfwd_ntt.so /home/u177856/hexl-fpga-2.0/device/fwd_ntt.cpp

fwd_ntt.cpp:532: Compiler Error: Compiler was unable to determine any resolvable address spaces. Please check if an appropriate board resource was specified.

Error: Optimizer FAILED.

Refer to /home/u177856/hexl-fpga-2.0/build/device/fwd_ntt/fwd_ntt-05528d-e9144b/libfwd_ntt_so.log for details.

the mentioned log file shows just:

Compiler Command: aoc -o /home/u177856/hexl-fpga-2.0/build/device/fwd_ntt/fwd_ntt-05528d-e9144b.aocx /home/u177856/hexl-fpga-2.0/build/device/fwd_ntt/fwd_ntt-443495-1d1729.spv -sycl -dep-files=/home/u177856/hexl-fpga-2.0/build/device/fwd_ntt/fwd_ntt-985b2b.d -output-report-folder=libfwd_ntt.so.prj -g -hardware
fwd_ntt.cpp:532: Compiler Error: Compiler was unable to determine any resolvable address spaces. Please check if an appropriate board resource was specified.

not exactly sure what to do with this ...

**Comment by fixerivan** [comment]
ok, sorry that was my mistake that i made in the script, fixed it now, thx
